## docker compose version
version: "3.8"
services:
  rabbitmq:
    #image-name:tag
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_1'
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_java_net

networks:
  rabbitmq_java_net:
    driver: bridge